### PR TITLE
Latest export of P1 automation scripts for EA

### PR DESCRIPTION
**Pull request by josh-p1**
XML file to be imported into EA as reference data. Contains automation scripts (e.g. update decomposition diagram with child elements not currently present).

### CODE REVIEW

**Comment by febiw** [comment]
This is pretty horrible! Is there a way to compile the source code into xml after pulling it down? I'd rather commit real code into here and then compile into xml before using in EA

**Comment by josh-p1** [comment]
> This is pretty horrible! Is there a way to compile the source code into xml after pulling it down? I'd rather commit real code into here and then compile into xml before using in EA

As far as I'm aware the conversion to and from XML is done solely in EA. The idea is to have users pull latest scripts into EA as easily as possible, will double check with Al if there's a way of replicating this conversion but I think we might need these XML files in source control...

**Comment by febiw** [comment]
Ok, that's fine for now but without putting raw code in source control you won't get collaborative devops benefit. You'll have to do dev in EA and I can't really review it as it's unreadable in xml

**Comment by josh-p1** [comment]
Ok. Might be worth adding in the raw code as well once the scripts are a bit more definitive

**Pull request merged**
